msgid ""
msgstr ""
"Project-Id-Version: openplotter\n"
"POT-Creation-Date: 2020-02-16 00:26+0100\n"
"PO-Revision-Date: 2020-02-29 16:18+0100\n"
"Last-Translator: \n"
"Language-Team: Spanish\n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 1.8.7.1\n"
"X-Poedit-Basepath: ../../..\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Poedit-SourceCharset: UTF-8\n"
"X-Crowdin-Project: openplotter\n"
"X-Crowdin-Language: es-ES\n"
"X-Crowdin-File: openplotter-network.po\n"
"X-Poedit-SearchPath-0: .\n"

#: networkPostInstall.py:30
msgid "Installing python packages..."
msgstr "Instalando paquetes de python..."

#: networkPostInstall.py:33 networkPostInstall.py:55 networkPostInstall.py:61
#: networkPreUninstall.py:31 networkPreUninstall.py:62
msgid "DONE"
msgstr "HECHO"

#: networkPostInstall.py:34 networkPostInstall.py:56 networkPostInstall.py:62
#: networkPreUninstall.py:32 networkPreUninstall.py:57
#: networkPreUninstall.py:63
msgid "FAILED: "
msgstr "ERROR: "

#: networkPostInstall.py:37
msgid "Editing config files..."
msgstr "Editando archivos de configuración..."

#: networkPostInstall.py:58
msgid "Setting version..."
msgstr "Ajustando versión..."

#: networkPreUninstall.py:28
msgid "Removing python packages..."
msgstr "Eliminando paquetes de python..."

#: networkPreUninstall.py:35
msgid "Restoring network Debian defaults..."
msgstr "Restaurando los valores predeterminados de red del sistema..."

#: networkPreUninstall.py:48
msgid "Removing openplotter-network service..."
msgstr "Eliminando servicio de Openplotter-red..."

#: networkPreUninstall.py:56
msgid "DONE. PLEASE REBOOT TO RESTORE NETWORK SETTINGS"
msgstr "Hecho. POR FAVOR REINICIE PARA RESTAURAR AJUSTES DE RED"

#: networkPreUninstall.py:59
msgid "Removing version..."
msgstr "Eliminando versión..."

#: openplotterNetwork.py:38
msgid "OpenPlotter Network"
msgstr "Red OpenPlotter"

#: openplotterNetwork.py:48
msgid "Help"
msgstr "Ayuda"

#: openplotterNetwork.py:51
msgid "Settings"
msgstr "Ajustes"

#: openplotterNetwork.py:54
msgid "Addresses and Ports"
msgstr "Direcciones y Puertos"

#: openplotterNetwork.py:56
msgid "Check Network"
msgstr "Comprobar red"

#: openplotterNetwork.py:59
msgid "Install Wifi Drivers"
msgstr "Instalar contr. Wifi"

#: openplotterNetwork.py:59
msgid "This does only help for unrecognized usb wlan type:"
msgstr "Esto sólo sirve para los tipos de wlan usb no reconocido:"

#: openplotterNetwork.py:66
msgid "Access Point"
msgstr "Punto de acceso]"

#: openplotterNetwork.py:134
msgid "Network Mode"
msgstr "Modo de red"

#: openplotterNetwork.py:139
msgid "AP"
msgstr "PA"

#: openplotterNetwork.py:149
msgid "5 GHz"
msgstr "5GHz"

#: openplotterNetwork.py:151
msgid "Add ethernet port to the AP"
msgstr "Añadir puerto ethernet al AP"

#: openplotterNetwork.py:174
msgid "Access Point Settings"
msgstr "Ajustes de punto de acceso"

#: openplotterNetwork.py:177
msgid "Sharing Internet device"
msgstr "Compartiendo internet desde"

#: openplotterNetwork.py:178
msgid "Update Sharing"
msgstr "Actualizar compartiendo"

#: openplotterNetwork.py:187
msgid ""
"SSID \n"
"maximum 32 characters"
msgstr ""
"SSID \n"
"máximo 32 caracteres"

#: openplotterNetwork.py:195
msgid ""
"Password \n"
"minimum 8 characters required"
msgstr ""
"Contraseña\n"
"mínimo 8 caracteres y robusta"

#: openplotterNetwork.py:204
msgid "Channel"
msgstr "Canal"

#: openplotterNetwork.py:316 openplotterNetwork.py:336
#: openplotterNetwork.py:341 openplotterNetwork.py:393
#: openplotterNetwork.py:397 openplotterNetwork.py:439
#: openplotterNetwork.py:470 openplotterNetwork.py:488
#: openplotterNetwork.py:625
msgid "none"
msgstr "nada"

#: openplotterNetwork.py:410
msgid "Wait please... "
msgstr "Un momento, por favor... "

#: openplotterNetwork.py:549
msgid "Your SSID must have a maximum of 32 characters and your password a minimum of 8."
msgstr "SSID de como máximo 32 caracteres y contraseña un mínimo de 8 y robusta."

#: openplotterNetwork.py:600
msgid ""
"OpenPlotter will reboot. If something goes wrong and you are on a headless system, you may not be able to reconnect again.\n"
"\n"
"Are you sure?"
msgstr ""
"Los cambios seran aplicados tras reiniciar.\n"
"\n"
"Si algo falla y esta usando un sistema sin pantalla (escritorio remoto),\n"
"tal vez no pueda volver a conectar.\n"
"\n"
"¿Está seguro?"

#: openplotterNetwork.py:601
msgid "Question"
msgstr "Pregunta"

#: openplotterNetwork.py:624 openplotterNetwork.py:625
msgid "wifi access point: "
msgstr "punto de acceso wifi: "

#: openplotterNetwork.py:642
msgid "wifi client: "
msgstr "cliente wifi: "

#: openplotterNetwork.py:655
msgid "running"
msgstr "trabajando"

#: openplotterNetwork.py:656
msgid "stopped"
msgstr "parado"

#: openplotterNetwork.py:670
msgid "IP address\n"
msgstr "Dirección IP\n"

#: openplotterNetwork.py:683
msgid "Installing Wifi modules... "
msgstr "Instalando módulos Wifi... "

#: openplotterNetwork.py:685
msgid "Done."
msgstr "Hecho."

#: openplotterNetwork.py:723
msgid "There are conflicts between server connections"
msgstr "Hay conflictos entre las siguientes conexiones del servidor"

#: openplotterNetwork.py:724
msgid "No conflicts between servers connections"
msgstr "No hay conflictos entre las conexiones de servidores"

#: ports.py:28
msgid "VNC Remote Desktop"
msgstr "Escritorio remoto VNC"

#: startup.py:46
msgid "Checking WIFI Access Point password..."
msgstr "Revisando contraseña del punto de acceso wi-fi..."

#: startup.py:68
msgid ""
"Security warning: You are using the default WIFI Access Point password.\n"
"Please change password in OpenPlotter Network."
msgstr "Advertencia de seguridad. Esta usando la contraseña basica del punto de aceso wi-fi. Por favor, cambiela por una mas robusta en OpenPlotter > red."

#: startup.py:69
msgid "changed"
msgstr "cambiado"
